'
'
'
@startuml req

hide circle
hide empty members
hide method

!function $req($name, $txt, $label, $id="")
    class "$name" as $label <<requirement>> {
        !if ($id == "")
            Id = $label
        !else
            Id=$id
        !endif
        Text = $txt
    }
!endfunction

!function $freq($name, $txt, $label, $id="")
    class "$name" as $label <<functionalRequirement>> {
        !if ($id == "")
            Id = $label
        !else
            Id=$id
        !endif
        Text = $txt
    }
!endfunction

!function $nfreq($name, $txt, $label, $id="")
    class "$name" as $label <<nonFunctionalRequirement>> {
        !if ($id == "")
            Id = $label
        !else
            Id=$id
        !endif
        Text = $txt
    }
!endfunction

!function $dcnstr($name, $txt, $label, $id="")
    class "$name" as $label <<designConstraint>> {
        !if ($id == "")
            Id = $label
        !else
            Id=$id
        !endif
        Text = $txt
    }
!endfunction

!function $nest($x, $y)
    $x +-- $y
!endfunction

!function $derive($x, $y)
    $x <.. $y : <<deriveReqt>>
!endfunction

!function $refine($x, $y)
    $x <.. $y : <<refine>>
!endfunction

!function $derivel($x, $y)
    $x <.. $y : <<deriveReqt>> link
!endfunction

@enduml
